/**
 * Shared conductor install primitives — the shim source and the npm-install
 * argument list, used by BOTH the build-time installer
 * (`scripts/prepare-conductor.ts`, which bundles conductor into the app) and
 * the runtime provisioner (`override.ts`, which installs a user-selected
 * version into `<userData>/conductor/<version>/` without an app update).
 *
 * Deliberately leaf-level: only `node:` imports, no electron/app/logger, so
 * the tsx-run build script can import it without dragging in Electron.
 */

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

export const CONDUCTOR_PACKAGE = "@houwert/conductor";

/** Marker file (next to `bin/`) recording which version an install tree holds. */
export const VERSION_MARKER = ".version";

/**
 * The conductor shim. Resolves the real entry point via `__dirname`-relative
 * lookup, so the same shim works in `native/conductor/bin/` (dev),
 * `<resourcesPath>/conductor/bin/` (packaged), and
 * `<userData>/conductor/<version>/bin/` (runtime override) without rewriting.
 *
 * Studio spawns the CLI entry point directly for its own calls. The shim is
 * what the agent gets, because it runs conductor from a Bash tool where an
 * `electron --run-as-node <entry>` invocation wouldn't survive being pasted
 * into a command line.
 */
export const SHIM_SCRIPT = `#!/usr/bin/env node
/* eslint-disable */
// Auto-generated by scripts/prepare-conductor.ts. Do not edit manually.
'use strict';

const path = require('path');
const { spawn } = require('child_process');

const CONDUCTOR_ENTRY = path.join(
  __dirname,
  '..',
  'node_modules',
  '@houwert',
  'conductor',
  'dist',
  'index.js',
);

const child = spawn(
  process.execPath,
  [CONDUCTOR_ENTRY].concat(process.argv.slice(2)),
  { stdio: 'inherit', env: process.env }
);
child.on('exit', (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }
  process.exit(code == null ? 1 : code);
});
child.on('error', (e) => {
  process.stderr.write('conductor-studio: failed to spawn conductor: ' + e.message + '\\n');
  process.exit(1);
});
`;

/** Write the shim into `<dir>/bin/conductor` (chmod +x). */
export function writeShim(installDir: string): void {
  const binDir = path.join(installDir, "bin");
  mkdirSync(binDir, { recursive: true });
  const binPath = path.join(binDir, "conductor");
  writeFileSync(binPath, SHIM_SCRIPT);
  chmodSync(binPath, 0o755);
}

/**
 * npm args to install `@houwert/conductor@<version>` as a self-contained flat
 * tree under `installDir`. `--ignore-scripts` skips conductor's postinstall;
 * `--no-package-lock` avoids writing a lockfile.
 */
export function registryInstallArgs(version: string, installDir: string): string[] {
  return [
    "install",
    `${CONDUCTOR_PACKAGE}@${version}`,
    "--prefix",
    installDir,
    "--ignore-scripts",
    "--no-package-lock",
  ];
}

/** Path to the shim binary inside an install tree. */
export function shimBinPath(installDir: string): string {
  return path.join(installDir, "bin", "conductor");
}

/** Path to the CLI's real JS entry point inside an install tree. */
export function entryPath(installDir: string): string {
  return path.join(installDir, "node_modules", "@houwert", "conductor", "dist", "index.js");
}
